export function downloadReportText(program, r) {
  if (!r) return;
  const lines = [
    "YOUNG CHRISTIAN DEVELOPMENT INITIATIVE (YCDI)",
    "POST-PROGRAM ACTIVITY REPORT — YCDI-PROG-001",
    "=".repeat(60),
    "",
    `Program title:        ${program.title}`,
    `Chapter:              ${program.chapter_name}`,
    `Program type:         ${program.type}`,
    `Program date:         ${program.date}`,
    `Report date:          ${r.report_date || "—"}`,
    `Reporting coordinator: ${r.reporting_coordinator || "—"}`,
    "",
    "A. PROGRAM OVERVIEW",
    "-".repeat(40),
    `Start time:           ${r.actual_start_time || "—"}`,
    `End time:             ${r.actual_end_time || "—"}`,
    `Venue confirmed:      ${r.venue_confirmed || "—"}`,
    `Pre-program prayer:   ${r.prayer_meet ? "Yes" : "No"}`,
    `Prayer attendees:     ${r.prayer_meeting_attendees ?? "—"}`,
    "",
    "B. ATTENDANCE AND REACH",
    "-".repeat(40),
    `Total attendance:     ${r.attendance ?? "—"}`,
    `Male:                 ${r.male_count ?? "—"}`,
    `Female:               ${r.female_count ?? "—"}`,
    `Ages 10-14:           ${r.age_10_14 ?? "—"}`,
    `Ages 15-19:           ${r.age_15_19 ?? "—"}`,
    `Ages 20-25:           ${r.age_20_25 ?? "—"}`,
    `First-time:           ${r.first_time_attendees ?? "—"}`,
    `Returning:            ${r.returning_attendees ?? "—"}`,
    `Volunteers deployed:  ${r.volunteers_deployed ?? "—"}`,
    `Schools represented:  ${r.schools_represented || "—"}`,
    "",
    "C. PROGRAM DELIVERY",
    "-".repeat(40),
    `Ran as planned:       ${r.program_ran_as_planned ? "Yes" : "No"}`,
    `Teaching method:      ${r.teaching_method || "—"}`,
    `Audience engagement:  ${r.audience_engagement || "—"}`,
    `Materials used:       ${r.materials_used || "—"}`,
    "",
    "Topics covered:",
    r.topics_covered || "—",
    "",
    `Mission test:         ${r.three_test_mission || "—"}`,
    `Quality test:         ${r.three_test_quality || "—"}`,
    `Safety test:          ${r.three_test_safety || "—"}`,
    "",
    "D. SPIRITUAL IMPACT",
    "-".repeat(40),
    `New commitments:      ${r.commitments_to_christ ?? "—"}`,
    `Recommitments:        ${r.recommitments ?? "—"}`,
    `Testimonials:         ${r.testimonials ?? "—"}`,
    `Joining fellowship:   ${r.students_joining_fellowship ?? "—"}`,
    "",
    "Testimonial summaries:",
    r.testimonials_detail || "None recorded",
    "",
    "Prayer requests:",
    r.prayer_requests || "None recorded",
    "",
    "Discipleship follow-up:",
    r.discipleship_followups || "None recorded",
    "",
    "E. SAFEGUARDING AND WELFARE",
    "-".repeat(40),
    `Two-volunteer rule:   ${r.two_volunteer_rule ? "Observed" : "NOT observed"}`,
    `Parental consents:    ${r.parental_consents ? "Yes" : "No"}`,
    `School permission:    ${r.school_permission ? "Yes" : "No"}`,
    `Incidents:            ${r.incidents > 0 ? `Yes (${r.incidents})` : "None"}`,
    r.incident_details ? `Incident details:\n${r.incident_details}` : "",
    `Welfare concerns:     ${r.welfare_concerns || "None"}`,
    `Referrals made:       ${r.referrals_made || "None"}`,
    "",
    "F. FINANCIAL ACCOUNTABILITY",
    "-".repeat(40),
    `Approved budget:      NGN ${(r.budget_approved || 0).toLocaleString()}`,
    `Actual expenditure:   NGN ${(r.actual_expenditure || 0).toLocaleString()}`,
    `Variance:             NGN ${((r.actual_expenditure || 0) - (r.budget_approved || 0)).toLocaleString()}`,
    r.variance_explanation ? `Variance explanation: ${r.variance_explanation}` : "",
    `Receipts obtained:    ${r.receipts_obtained ? "Yes" : "No"}`,
    `Outstanding payments: ${r.outstanding_payments || "None"}`,
    "",
    "G. LESSONS LEARNED AND FOLLOW-UP",
    "-".repeat(40),
    "What went well:",
    r.what_went_well || "—",
    "",
    "What could be improved:",
    r.what_could_improve || "—",
    "",
    "Recommendations:",
    r.recommendations || "—",
    "",
    "Follow-up actions:",
    r.follow_up_actions || "—",
    "",
    `Next program suggested: ${r.next_program_suggested || "—"}`,
    "",
    "=".repeat(60),
    `Report generated: ${new Date().toLocaleString()}`,
    "YCDI Programme Hub — ycdinigeria.org",
  ].filter((v) => v !== undefined).join("\n");

  const blob = new Blob([lines], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `YCDI_Report_${program.title.replace(/[^a-z0-9]/gi, "_").slice(0, 40)}_${program.date}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
